name: Desktop App Test

on:
    workflow_dispatch:
    push:
        branches: [ "feature/tls" ]

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - uses: FedericoCarboni/setup-ffmpeg@v3
              id: setup-ffmpeg
              with:
                ffmpeg-version: release
                architecture: 'x64'
                github-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}
            - name: Use Node.js
              uses: actions/setup-node@v3
            - name: Activate Hyper-V
              run: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All -NoRestart
            - name: Download Dependencies
              run: |
                curl -L -o WindowsApplicationDriver_1.2.1.msi https://github.com/microsoft/WinAppDriver/releases/download/v1.2.1/WindowsApplicationDriver_1.2.1.msi
                curl -L -o python-3.12.4-amd64.exe https://www.python.org/ftp/python/3.12.4/python-3.12.4-amd64.exe
                curl -L -o thunderbird-setup.exe "https://download.mozilla.org/?product=thunderbird-128.0esr-SSL&os=win64&lang=en-US"
                curl -L -o Docker-Desktop-Installer.exe "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe"
            - name: Enable developer-mode
              run : reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /t REG_DWORD /f /v "AllowDevelopmentWithoutDevLicense" /d "1" 
            - name: Install Dependencies
              run: |
                Start-Process msiexec "/i D:\a\WendzelNNTPd\WendzelNNTPd\WindowsApplicationDriver_1.2.1.msi /norestart /qn" -Wait
                Write-Output "WinAppDriver installation complete."
                Start-Process 'D:\a\WendzelNNTPd\WendzelNNTPd\Docker-Desktop-Installer.exe' -Wait -PassThru -ArgumentList 'install', '--accept-license', '--backend=hyper-v', '--always-run-service', '--quiet', '--no-windows-containers'
                Write-Output "Docker installation complete."
                Start-Process "D:\a\WendzelNNTPd\WendzelNNTPd\python-3.12.4-amd64.exe" -ArgumentList "/i /qn /S /AllUsers /norestart" -Wait -PassThru 
                Write-Output "Python installation complete."
                Start-Process "D:\a\WendzelNNTPd\WendzelNNTPd\thunderbird-setup.exe" -ArgumentList "/i /qn /S /AllUsers /norestart" -Wait -PassThru 
                Write-Output "Thunderbird installation complete."
                python -m ensurepip --upgrade
                npm i --location=global appium
                pip install Appium-Python-Client
                pip install -U pytest
                appium driver install windows
                Write-Output "installation complete."     
            - name: Add WinAppDriver firewall rule
              run: netsh advfirewall firewall add rule name="WinAppDriver remote" dir=in action=allow protocol=TCP localport=4723
            - name: Build WendzelNNTPd docker container
              run: |
                & $Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon .
                docker build -f ./docker/Dockerfile_GitHub -t wendzelnntpd:latest . 
            - name: Run WendzelNNTPd docker container
              run: docker run --name wendzelnntpd --rm -it -d -p 119:119 wendzelnntpd:latest
            - name: Add videos directory for appium tests
              run: New-Item D:\a\WendzelNNTPd\WendzelNNTPd\user-acceptance-test\videos\ -ItemType Directory -ea 0
            - name: Run appium
              run: |
                Start-Process "C:\npm\prefix\appium" -PassThru
                docker -v
                python -m pytest D:\a\WendzelNNTPd\WendzelNNTPd\user-acceptance-test\test.py 
            - uses: actions/upload-artifact@v4
              name: Upload videos
              if: always()
              with:
                name: videos
                path: D:\a\WendzelNNTPd\WendzelNNTPd\user-acceptance-test\videos\
                retention-days: 1